version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.8.14-management
    networks:
      - messageservice
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - messageservice
    volumes:
      - mongodb_data:/data/db

  message-api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - messageservice
    ports:
      - "1200:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - rabbitmq
      - mongodb

  elasticsearch:
    container_name: message-service-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports:
      - "9200:9200"
    volumes:
      - message-service-elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - messageservice

  kibana:
    container_name: message-service-kibana
    image: docker.elastic.co/kibana/kibana:7.6.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - messageservice

networks:
  messageservice:


volumes:
  mongodb_data:
  message-service-elasticsearch-data:
