version: '3.7'

services:
  message-api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - messageservice
    ports:
      - "1200:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  messageservice:


